name: Dev_CI_Backend
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 11.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Build project
      run: npm run build
    - name: Run Tests
      run: export CI=true && npm run test -- --coverage
      env:
        MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
